services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist
    ports:
      - 8228:8000
    volumes:
      - ${BASEDIR}/docker/tubearchivist/media:/youtube
      - ${BASEDIR}/docker/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200       # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis            # don't add protocol
      - HOST_UID=0
      - HOST_GID=0
      - TA_HOST=${TA_HOST}                    # set your host name
      - TA_USERNAME=tubearchivist             # your initial TA credentials
      - TA_PASSWORD=${TA_PASSWORD}            # your initial TA credentials
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}  # set password for Elasticsearch
      - TZ=America/Vancouver                  # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - archivist-network
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ${BASEDIR}/docker/tubearchivist/redis:/data
    networks:
      - archivist-network
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3 # workaround seccomp not available error
    container_name: archivist-es
    restart: always
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${BASEDIR}/docker/tubearchivist/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    networks:
      - archivist-network
networks:
  archivist-network:
    driver: bridge
