services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3333:3000
    volumes:
      - ${BASEDIR}/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always