services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5388:80/tcp"
      - "5389:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - ${BASEDIR}/docker/adguard/work:/opt/adguardhome/work
      - ${BASEDIR}/docker/adguard/conf:/opt/adguardhome/conf
    restart: always
