services:
  upsnap:
    container_name: upsnap
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: always
    volumes:
      - /root/docker/upsnap/data:/app/pb_data
    environment:
       - TZ=America/Vancouver # Set container timezone for cron schedules
       - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
       - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5555"
    healthcheck:
      test: curl -fs "http://localhost:5555/api/health" || exit 1
      interval: 10s