services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: condor
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-exit-node --advertise-routes=192.168.1.0/24
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    volumes:
      - ${BASEDIR}/docker/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    pre_stop:
      - command: tailscale logout
    restart: always
