version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ${ST_HOSTNAME}
    environment:
      - PUID=${ST_PUID}
      - PGID=${ST_PGID}
      - STGUIADDRESS=
      - PCAP=cap_chown,cap_fowner+ep
    volumes:
      - ${ST_ROOT_SYNC_DIR}:/var/syncthing
    # ports:
    #   - 38384:8384 # Web UI
    #   - 22000:22000/tcp # TCP file transfers
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3